#ifndef MPSSE_H
#define MPSSE_H

#define MSB_RISING_EDGE_CLK_BYTE_OUT  0x10
#define MSB_FALLING_EDGE_CLK_BYTE_OUT 0x11
#define MSB_RISING_EDGE_CLK_BIT_OUT   0x12
#define MSB_FALLING_EDGE_CLK_BIT_OUT  0x13
#define MSB_RISING_EDGE_CLK_BYTE_IN   0x20
#define MSB_RISING_EDGE_CLK_BIT_IN    0x22
#define MSB_FALLING_EDGE_CLK_BYTE_IN  0x24
#define MSB_FALLING_EDGE_CLK_BIT_IN   0x26


#endif //MPSSE_H